### PR TITLE
fix: fix redundant check for depositWithPermit

### PR DESCRIPTION
**Pull request by Jung0x12**
# Summary
Optimization: Redundant Checks in depositWithPermit Function

Issue: https://www.notion.so/islelabs/Smart-Contract-Audit-Draft-Response-v1-0-03839677f03540238c0d167fdeee2e7e?pvs=4#67574839c68649a38ff85322ce818154

# Description
The current implementation of the `depositWithPermit` function uses the `deposit` function, which performs redundant checks that depositWithPermit has already handled. In this implementation, we check zero address of receiver and maxDeposit twice.

# Fix
Refactor `depositWithPermit` to remove redundant check.

# Verification
- Run tests
   `DepositWithPermit_Pool_Integration_Concrete_Test`
   `MintWithPermit_Pool_Integration_Concrete_Test`

### CODE REVIEW

**Comment by LouisTsai-Csie** [comment]
LGTM, I verify by checking the test locally.

But the `Pool::depositWithPermit` is also called in `MintWithPermit_Pool_Integration_Concrete_Test`, so it should be included in the verification part as well.

**Review by LouisTsai-Csie — APPROVED** [review]
LGTM, I verify by checking the test locally.

But the `Pool::depositWithPermit` is also called in `MintWithPermit_Pool_Integration_Concrete_Test`, so it should be included in the verification part as well.

**Comment by Jung0x12** [comment]
> LGTM, I verify by checking the test locally.
> 
> But the `Pool::depositWithPermit` is also called in `MintWithPermit_Pool_Integration_Concrete_Test`, so it should be included in the verification part as well.

**Comment by Jung0x12** [comment]
Right, I updated the Verification description, thx

**Pull request merged**
