### PR TITLE
fix: reset isImpaired to false when remove loan impairment

### PR DESCRIPTION
**Pull request by Jung0x12**
# Summary
Inconsistent Loan Impairment Handling Due to Missing Reset of isImpaired Flag

[Issue](https://www.notion.so/islelabs/Smart-Contract-Audit-Draft-Response-v1-0-03839677f03540238c0d167fdeee2e7e#ac0228e633b94fe382b96bfc9383dfeb)

# Description
The removeLoanImpairment function in the LoanManager contract fails to reset the isImpaired flag to false after removing a loan's impairment. As a result, the loan remains incorrectly marked as impaired, leading to inconsistencies in how the loan is managed by the contract. This can cause incorrect calculations of unrealized losses and improper handling of loan defaults.

# Fix
Reset isImpaired to false when remove loan impairment

# Verification
- Key Invariant
   After reset to false，the correct `netInterest`, `netLateInterest` and `protocolFees` will be get in triggerDefault.
- Run tests
   test_RemoveLoanImpairment
   test_TriggerDefault_WhenLoanRemoveImpair

I add a new test case `test_TriggerDefault_WhenLoanRemoveImpair` to simulate remove an impaired loan. This case can check interests and remainingLosses are correct after the `isImpaired` flag set back to false.

After this fixing, the issue [Incorrect Accounting on Loan Removal](https://www.notion.so/islelabs/Smart-Contract-Audit-Draft-Response-v1-0-03839677f03540238c0d167fdeee2e7e?pvs=4#6512162162864dbba56f906767b448dc) also not happen anymore.

### CODE REVIEW

**Comment by LouisTsai-Csie** [comment]
Hi @Jung0x12 , I noticed there is a forced push, I compare the changes and find the difference lies in the `.github/workflows/update-accounting.yml`. Do you modify any file other than the `contracts/LoanManager.sol`?

**Review by LouisTsai-Csie — COMMENTED** [review]
> After reset to false，the correct netInterest, netLateInterest and protocolFees will be get in triggerDefault.

This is the description in the PR, could we compare these value before and after these operation to make sure the `LoanManager::removeImpairment` will not affect the calculation.

If the test case can compare these values, then the issue can be detected before audit.

Next, if the `isImpaired` flag is reset correctly, we can solve this [issue](https://www.notion.so/islelabs/Incorrect-Accounting-on-Loan-Removal-f320d86778e64cf497c559cfdf424f80?pvs=4) as well?

**Comment by Jung0x12** [comment]
> I noticed there is a forced push, I compare the changes and find the difference lies in the .github/workflows/update-accounting.yml. Do you modify any file other than the contracts/LoanManager.sol?

I rebase from the main branch to align it, didn't make any change other than LoanManager.

**Comment by Jung0x12** [comment]
> If the test case can compare these values, then the issue can be detected before audit.
Sure I can add new test case to make sure netInterest, netLateInterest and protocolFees correctly.

**Comment by LouisTsai-Csie** [comment]
> > I noticed there is a forced push, I compare the changes and find the difference lies in the .github/workflows/update-accounting.yml. Do you modify any file other than the contracts/LoanManager.sol?
> 
> I rebase from the main branch to align it, didn't make any change other than LoanManager.

Got it, my first time being a reviewer XD.

**Review by kevinsslin — APPROVED** [review]

**Pull request merged**
